Achievement service and publisher
CorporationX/achievement_service pull request #153
Opened 2024-08-11 20:37 UTC by legionerkz

2024-08-14 12:02 UTC, Nikita2768 commented on src/main/java/faang/school/achievement/config/redis/RedisConfig.java
> +@RequiredArgsConstructor
Привет) Здесь вообще нужна эта аннотация? Она ведь не работает с не финальными полями? Да и принципе тебе здесь инжектить нечего

2024-08-14 12:02 UTC, Nikita2768 commented on src/main/java/faang/school/achievement/publisher/AchievementPublisher.java
> +public class AchievementPublisher implements MessagePublisher<UserAchievement> {
А нужен ли нам вообще этот интерфейс? Сервис занимается только достижениями и вроде как, больше ни каких доп функций ему не предполагается. Следовательно оповещать кроме как о достижениях не предполагается. Поэтому интерфейс выглядит как-будто излишней абстракцией

2024-08-14 12:02 UTC, Nikita2768 commented on src/main/java/faang/school/achievement/config/redis/RedisConfig.java
> +    @Value("${data.redis.chanel.achievement}")
data:
    redis:
      port: 6379
      host: localhost
      channel:
        achievement: achievement_channel
         follower: follower_channel
 У тебя путь по другому написан, ты пробовал запускать проект, работает?

2024-08-14 15:45 UTC, malkov34 commented on src/main/java/faang/school/achievement/config/redis/RedisConfig.java
> +        RedisStandaloneConfiguration config = new RedisStandaloneConfiguration(host, port);
https://www.baeldung.com/spring-data-redis-properties

можно вынести в конфиги и использовать Lettuce

2024-08-14 15:45 UTC, malkov34 commented on src/main/java/faang/school/achievement/controller/AchievementController.java
> +    @ResponseStatus(HttpStatus.OK)
Статусы необзятельны

2024-08-14 15:45 UTC, malkov34 commented on src/main/java/faang/school/achievement/dto/UserAchievementEvent.java
> +    private LocalDateTime createdAt;
не думаю, что время создания ачивки является нужной инфой при передаче в сервис нотификации

2024-08-19 04:37 UTC, pablo023 requested changes
Чуть чуть лишнего убрать надо, и прокомменти, что насчет ачивмент топика в редис конфиге

2024-08-19 04:37 UTC, pablo023 commented on src/main/java/faang/school/achievement/config/redis/RedisConfig.java
> +@RequiredArgsConstructor
Согласен

2024-08-19 04:37 UTC, pablo023 commented on src/main/java/faang/school/achievement/config/redis/RedisConfig.java
> +    @Value("${data.redis.chanel.achievement}")
?

2024-08-19 04:37 UTC, pablo023 commented on src/main/java/faang/school/achievement/dto/AchievementFilterDto.java
> +@Data
Тебе не нужна тут дата, ты не используешь всего , что она генерит

2024-08-19 04:37 UTC, pablo023 commented on src/main/java/faang/school/achievement/publisher/AchievementPublisher.java
> +public class AchievementPublisher implements MessagePublisher<UserAchievement> {
Возможно не интерфейс, а абстрактный класс подошел бы, с какой-то логикой, если она есть

2024-08-19 04:37 UTC, pablo023 commented on src/main/resources/application.yaml
> +  port: 8095
Это не надо пушить, я думаю. Разберись, почему у тебя на 8085 не работает, и сделай, чтобы работало

2024-09-10 00:41 UTC, merged