Achievement Cache
CorporationX/achievement_service pull request #154
Opened 2024-08-11 20:39 UTC by legionerkz

2024-08-14 14:01 UTC, Nikita2768 commented on src/main/java/faang/school/achievement/model/Achievement.java
> +@Getter
Подскажи, пожалуйста, а зачем это нужно? Data ведь предоставляет тот же функционал, только немного больше

2024-08-14 14:01 UTC, Nikita2768 commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +    @Scheduled(cron = "${cache.achievement.update-schedule}")
Если я правильно понимая, то, при добавлении нового достижения нам нужно в коде создать его обработчик, а это значит, что нам в любом случае нужно будет заново компилировать проект. Если я прав получается он просто так будет каждый час гонять обновление кэша

2024-08-14 14:16 UTC, legionerkz commented on src/main/java/faang/school/achievement/model/Achievement.java
> +@Getter
Была проблема с маппингом этого энтити с методом toString().  @Data is a convenient shortcut annotation that bundles the features of [@ToString](https://projectlombok.org/features/ToString), [@EqualsAndHashCode](https://projectlombok.org/features/EqualsAndHashCode), [@Getter / @Setter](https://projectlombok.org/features/GetterSetter) and [@RequiredArgsConstructor](https://projectlombok.org/features/constructor)

2024-08-14 14:17 UTC, legionerkz commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +    @Scheduled(cron = "${cache.achievement.update-schedule}")
Новое достижение будет просто сохраняться в базе - через контроллер -> сервис.
Этим методом мы просто заново подтянем в кэш новое достижение.

2024-08-14 14:18 UTC, malkov34 commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +    @Scheduled(cron = "${cache.achievement.update-schedule}")
Я бы через шедулер не делал, так как:
1. Если добавление ачивок происходит через миграции, то все равно надо приложение останавливать.
2. Если через ui админки, то тогда надо явно обновлять в моменте добавления новой ачивки

В своей мр, я вообще этот момент не стал обрабатывать. Непонятны дальнешие кейсы использования

2024-08-14 14:18 UTC, malkov34 commented on src/main/resources/application.yaml
> +  port: 8095
случайно попало?

2024-08-14 14:20 UTC, legionerkz commented on src/main/resources/application.yaml
> +  port: 8095
на 85 порте не поднимался у меня проект. поставил 95

2024-08-14 14:46 UTC, legionerkz commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +    @Scheduled(cron = "${cache.achievement.update-schedule}")
А в чем тогда смысл статического кэша? Он же должен обновлятся.

2024-08-14 15:48 UTC, malkov34 commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +    @Scheduled(cron = "${cache.achievement.update-schedule}")
> А в чем тогда смысл статического кэша? Он же должен обновлятся.

Тут бльше вопрос, а как он обновляется в бд?
Вот три возможных кейса:
1. Руками (такое себе...) На этот случай твоя обработка будет полезна, но с уменьшением крона. Чтобы данные всегда были актуальны
2. UI
3. Миграции

2024-08-14 15:48 UTC, malkov34 commented on src/main/resources/application.yaml
> +  port: 8095
> на 85 порте не поднимался у меня проект. поставил 95

из мрки стоит убрать, так как локальные правки не должны попадать в общую ветку

2024-08-19 04:23 UTC, pablo023 requested changes

2024-08-19 04:23 UTC, pablo023 commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
Эта задача делается через редис, не через хэш мапу джава, так как тебе нужно распределенное хранилище. Вот это вот не будет расширяемым решением. Ко всему прочему, нужно указать TTL для объектов, которые в кэше хранятся. Иначе они там так и будут жить, просто дублируя бд.

2024-08-19 04:23 UTC, pablo023 commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +    }
Имеет наверное смысл не апдейтить его полностью, а только те изменения вносить, которые после последнего апдейта производились.

2024-08-19 04:23 UTC, pablo023 commented on src/main/resources/application.yaml
> +  port: 8095
Уместно

2024-08-19 04:23 UTC, pablo023 commented on src/main/resources/application.yaml
> +      update-schedule : "@hourly"
Это сработает, но не для высоконагруженной распределенной системы. Во-первых, из-за подтягивания лишних данных, как сейчас у тебя работает, т.к. весь кэш обновляется. В целом, смотри, если данные обновляются в базе данных после того, как кэш уже был обновлён, пользователи будут получать устаревшую информацию до следующего обновления. В высоконагруженных системах это может серьёзно испортить пользовательский опыт. Когда мы обновляем кэш по расписанию, часто приходится загружать все данные, даже если изменилась только небольшая часть. Это лишняя нагрузка на базу данных и ненужное использование ресурсов. Вместо того чтобы обновлять кэш по расписанию, мы можем обновлять его в ответ на события. Например, когда в базе данных добавляется или изменяется достижение, мы сразу обновляем кэш.

2024-09-10 00:41 UTC, merged