Feature запрос достижений
CorporationX/achievement_service pull request #179
Opened 2024-08-18 21:20 UTC by grisatkac

Запрос достижений
https://faang-school.atlassian.net/browse/BJS2-25794

2024-08-20 23:27 UTC, pablo023 requested changes
В целом окей. Но давай задумываться о том, что происходит, когда мы используем findAll - оттуда же вылезти может что-то страшное, несколько миллионов сущностей.

2024-08-20 23:27 UTC, pablo023 commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +                .toList();
Добавь пагинацю. У тебя ачивок может несколько миллионов быть, даже с фильтром. Это будет жестко - отдавать их вот так все разом. Просто не прогрузит с херовым интернетом даже

2024-09-03 14:49 UTC, pablo023 commented
Не обработал коммент про пагинацию

2024-09-08 20:05 UTC, grisatkac commented
> Не обработал коммент про пагинацию

добавил

2024-09-10 23:44 UTC, merged