BJS2-15676
CorporationX/achievement_service pull request #184
Opened 2024-08-19 19:24 UTC by Caveri95

- Создана конфигурация Redis, добавлен топик WRITER
- Описан сервис для работы с достижениями
- Создан обработчик событий из Redis
- Написаны тесты

2024-08-25 01:39 UTC, pablo023 requested changes

2024-08-25 01:39 UTC, pablo023 commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
Вообще, это через редис делается, через хэш-мапу не подойдет для высоконагруженой системы.

2024-08-25 01:39 UTC, pablo023 commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +        this.initCache();
Он у тебя одно и то же будет делать, как будто не имеет это смысла. Пускай обновляет только с той инфой, которая новая после предыдущего обновления.

2024-08-25 01:39 UTC, pablo023 commented on src/main/java/faang/school/achievement/config/RedisCredentials.java
> +    }
Не надо таким заниматься, выноси в отдельные классы

2024-08-25 01:39 UTC, pablo023 commented on src/main/java/faang/school/achievement/config/RedisCredentials.java
> +    }
И дата тебе там не нужна, ты не используешь всего, что она генерирует.

2024-08-25 01:39 UTC, pablo023 commented on src/main/java/faang/school/achievement/redis/handler/WriterAchievementHandlerPost.java
А зачем он тебе нужен, если ты по сути тут просто одну строку вызова сервиса засовываешь в методы?

2024-08-27 19:48 UTC, Caveri95 commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
исправил на кеш в Redis

2024-08-27 19:52 UTC, Caveri95 commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +        this.initCache();
Не понял, что значит после предыдущего обновления? Я один раз при запуске в кеш поместил все, что есть в БД. В след раз мне когда обновить кеш? Опять же придется все вытаскивать из БД и смотреть, что было в кеше, а что нового появилось?

2024-08-27 19:52 UTC, Caveri95 commented on src/main/java/faang/school/achievement/config/RedisCredentials.java
> +    }
окей

2024-08-27 20:15 UTC, Caveri95 commented on src/main/java/faang/school/achievement/redis/handler/WriterAchievementHandlerPost.java
Он реализуется, когда у нас топик приходит событие на создание поста и отрабатывает конкретная ачивка WRITER. Так понимаю, что ачивок может быть несколько на случай создания постов и для каждой нужна реализация. Вроде так

2024-08-28 03:46 UTC, pablo023 commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +        this.initCache();
Ну у тебя по крону вызывается метод инит, который идет, и всё из базы тащит. Нам же не нужен весь контент базы, а только то, что мы ещё не тянули. Иначе не очень оптимально - просто тащим из БД то, что итак в кэше уже есть

2024-08-28 03:49 UTC, pablo023 requested changes

2024-08-28 03:49 UTC, pablo023 commented on src/main/java/faang/school/achievement/redis/handler/WriterAchievementHandlerPost.java
Я имею ввиду - зачем тебе нужен метод, который просто дёргает сервис? Ты можешь по сути сам сервис и дергать, без этого метода. А то он не содержит же ничего кроме того, что ты сервис этот дергаешь.

2024-08-28 03:49 UTC, pablo023 commented
И конфликты надо поправить

2024-08-28 18:50 UTC, Caveri95 commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +        this.initCache();
Исправил

2024-08-29 09:51 UTC, merged