BC-5696 Получение достижения "Организатор"
CorporationX/achievement_service pull request #20
Opened 2023-08-29 12:50 UTC by czar777

2023-09-05 17:20 UTC, Monono7 commented on src/main/java/faang/school/achievement/config/RedisConfig.java
> +public class RedisConfig {
напиши лучше полностью RedisConfiguration)

2023-09-08 08:39 UTC, InnMish requested changes

2023-09-08 08:39 UTC, InnMish commented on src/main/java/faang/school/achievement/AchievementServiceApp.java
> +@PropertySource(value = "classpath:resource_achievement/achievement.properties", encoding = "UTF-8")
А это Влад подсказал так делать? Мне что-то не очень нравится, что у нас есть и ямл, и пропертис( 

В спринге можно настроить так, чтобы один ямл подтягивался в другой ямл, и спринг будет их использовать вместе в одном контексте. Может, так попробуем сделать? Просто, чтобы у нас все было унифицировано.

То есть создаешь не пропертис, а ямл файл, и при этом в общий ямл, где конфиги, этот новый инжектишь. Там будет что-то вроде такой настройки 
```
spring:
  config:
    import: classpath:achievement.yml
```
И тогда вот эта аннотация будет не нужна, а доступ к полям также через Value сможем получить, потому что новый маленький ямл как бы расширяет общий большой ямл

2023-09-08 08:39 UTC, InnMish commented on src/main/java/faang/school/achievement/hundler/EventHandler.java
> +public interface EventHandler {
Тут давай сразу дженерик влепим, на будущее, чтобы с разными эвентами могли работать

2023-09-08 08:39 UTC, InnMish commented on src/main/java/faang/school/achievement/hundler/AbstractOrganizerAchievementHandler.java
> +public abstract class AbstractOrganizerAchievementHandler implements EventHandler {
Давай сделаем абстрактный класс для всех, чтобы он не только с этим достижением работал. 
Тут тоже дженерик сделаем, ну и название поправим, чтобы без Organizer было. Этот абстрактный для всех - иначе какой смысл в его абстрактности)

2023-09-08 08:39 UTC, InnMish commented on src/main/java/faang/school/achievement/hundler/AbstractOrganizerAchievementHandler.java
> +        Achievement achievement = achievementService.getAchievement(title);
По-моему, можем использовать кэш)

2023-09-08 08:39 UTC, InnMish commented on src/main/java/faang/school/achievement/hundler/AbstractOrganizerAchievementHandler.java
> +    public void handle(InviteSentEventDto inviteSentEventDto) {
Соответственно тут тоже будет дженерик

2023-09-08 08:39 UTC, InnMish commented on src/main/java/faang/school/achievement/hundler/AbstractOrganizerAchievementHandler.java
> +        }
Вот эту конкретную логику должен делать не абстрактный хендлер 
Иначе всем остальным тоже придется свои абстрактные классы писать
Давай тут подумаем, как этот класс сделать общим для всех, а логику по организатору перенести в OrganizerAchievementHandler

2023-09-08 08:39 UTC, InnMish commented on src/main/java/faang/school/achievement/service/AchievementProgressService.java
> +    }
Сюда еще бы логику проверки перенести  
Та часть, которая в методе getAchievementProgress в хендлере в блоке if, я думаю, можно сюда перетащить

2023-09-08 11:07 UTC, czar777 commented on src/main/java/faang/school/achievement/hundler/AbstractOrganizerAchievementHandler.java
> +        Achievement achievement = achievementService.getAchievement(title);
я смотрю кэш в сервисе

2023-09-10 15:40 UTC, InnMish approved these changes

2023-09-10 15:41 UTC, merged