Feature bjs2 16049
CorporationX/achievement_service pull request #214
Opened 2024-09-04 09:32 UTC by grisatkac

https://faang-school.atlassian.net/browse/BJS2-16049

2024-09-10 01:06 UTC, pablo023 requested changes
В основном надо фиксануть конфликты, и ответить по поводу дто

2024-09-10 01:06 UTC, pablo023 commented on src/main/java/faang/school/achievement/config/redis/RedisConfig.java
> +    ChannelTopic postChannelTopic() {
Модификатор доступа?

2024-09-10 01:06 UTC, pablo023 commented on src/main/java/faang/school/achievement/dto/AchievementProgressDto.java
> +    }
Нам в дто это разве нужно? Это же объект, чтобы просто передавать информацию, зачем нам тут логика?

2024-09-10 01:10 UTC, pablo023 reviewed
Если ты уверен насчет логики инкрементации в дто - можем вмержить, но что-то я тут не пойму. Отпиши мне по этому поводу.

2024-09-10 01:10 UTC, pablo023 commented on src/main/java/faang/school/achievement/dto/AchievementProgressDto.java
> +    }
Аналогичный вопрос, как в ПР в другой сервис. Нам это тут надо?

2024-09-10 19:30 UTC, grisatkac commented on src/main/java/faang/school/achievement/dto/AchievementProgressDto.java
> +    }
> Аналогичный вопрос, как в ПР в другой сервис. Нам это тут надо?

я увидел, что метод increment был в сущности AchievementProgress и решил перетянуть его в дтошку
использую этот метод в абстрактном хэндлере AbstractAchievementHandler
если посчитаешь лучше использовать условно  ++ вместо increment(), чтобы увеличивать прогресс ачивки, то поменяю)

2024-09-10 19:30 UTC, grisatkac commented on src/main/java/faang/school/achievement/config/redis/RedisConfig.java
> +    ChannelTopic postChannelTopic() {
> Модификатор доступа?

упс, добавлю паблик

2024-09-10 19:30 UTC, grisatkac commented on src/main/java/faang/school/achievement/dto/AchievementProgressDto.java
> +    }
> Нам в дто это разве нужно? Это же объект, чтобы просто передавать информацию, зачем нам тут логика?

ответил выше

2024-09-29 19:54 UTC, grisatkac commented
> Если ты уверен насчет логики инкрементации в дто - можем вмержить, но что-то я тут не пойму. Отпиши мне по этому поводу.

конфликты разрешил
после разрешения конфликтов оказалось, что этот метод increment не используется, поэтому я его удаляю)

2024-09-30 05:24 UTC, merged