- v1 EvilCommenter  BJS2-26181
CorporationX/achievement_service pull request #233
Opened 2024-10-15 11:04 UTC by Silencemess1ah

- v1 some todo's to be done + tests

2024-10-17 21:20 UTC, GusevVrn reviewed
ну как смог, можно подумать над еще большей абстракции, но надо посмотреть еще таски, какие примерно будут и что там хотят чтоб забубенить.
я чет уже все на сегодня

2024-10-17 21:20 UTC, GusevVrn commented on src/main/java/faang/school/achievement/config/redis/RedisConfiguration.java
> +                redisProperties.getPort());
убери

2024-10-17 21:20 UTC, GusevVrn commented on src/main/java/faang/school/achievement/controller/achievement/AchievementController.java
> +@RequestMapping("/v1/achievements/")
тут слеш убери

2024-10-17 21:20 UTC, GusevVrn commented on src/main/java/faang/school/achievement/controller/achievement/AchievementController.java
> +    @GetMapping("{achievementId}")
а тут добавь

2024-10-17 21:20 UTC, GusevVrn commented on src/main/java/faang/school/achievement/dto/EventDto.java
> +public abstract class EventDto {
опять он

2024-10-17 21:20 UTC, GusevVrn commented on src/main/java/faang/school/achievement/dto/comment/CommentEventDto.java
> +@EqualsAndHashCode(callSuper = true)
зачем

2024-10-17 21:20 UTC, GusevVrn commented on src/main/java/faang/school/achievement/handler/EventHandler.java
> +public interface EventHandler {
зачем он нужен без методов?

2024-10-17 21:20 UTC, GusevVrn commented on src/main/java/faang/school/achievement/publisher/achievement/UserAchievementPublisher.java
> +        log.debug("Sent message with id : {} in {} channel", message.getId(),
ну тут так же у меня первая ассоциация что ты айдишник сообщения печатаешь

2024-10-17 21:20 UTC, GusevVrn commented on src/main/java/faang/school/achievement/publisher/achievement/UserAchievementPublisher.java
> +@Builder
копипаста( лишние же

2024-10-17 21:20 UTC, GusevVrn commented on src/main/java/faang/school/achievement/listener/comment/CommentEventListener.java
> +            log.debug("Sending sending comment event to all handlers");
Sending sending sending

2024-10-17 21:20 UTC, GusevVrn commented on src/main/java/faang/school/achievement/handler/comment/EvilCommenterAchievementHandler.java
> +    private static final int POINTS_TO_ACHIEVE = 100;
это в конфиг

2024-10-17 21:20 UTC, GusevVrn commented on src/main/java/faang/school/achievement/handler/comment/EvilCommenterAchievementHandler.java
> +        Achievement evilCommenter = achievementRepository.findById(9L).orElseThrow();
ну такое себе, я конечно понял, но все равно такое себе

2024-10-18 20:10 UTC, Silencemess1ah commented on src/main/java/faang/school/achievement/config/redis/RedisConfiguration.java
> +                redisProperties.getPort());
Почему? Я наоборот думал что лучше выставить такое вдруг поменяем хост порт ну и на будущее красивее выглядит, я сначала все так и написал что он по дефолту выставляет порт и хоста который у нас указан ;/

2024-10-18 20:11 UTC, Silencemess1ah commented on src/main/java/faang/school/achievement/dto/EventDto.java
> +public abstract class EventDto {
Кто он? ) Ну вдруг надо будет общую какую логику добавить можно id шник выставить например для всех или еще что понадобиться, я ж на будущее, ну ладно

2024-10-18 20:12 UTC, Silencemess1ah commented on src/main/java/faang/school/achievement/dto/comment/CommentEventDto.java
> +@EqualsAndHashCode(callSuper = true)
Потому что если @Builder по моему ставишь он ругается что нету этого уберу общий дто уйдет оно

2024-10-18 20:14 UTC, Silencemess1ah commented on src/main/java/faang/school/achievement/handler/EventHandler.java
> +public interface EventHandler {
Ну блин, пока не придумано что сюда вынести тут логика такая как рассказали так и сделал с заделом на будущее у нас один общий интерфейс от него абстрактные классы (категории) у них уже свои хэндлеры конкретных ачивок, задумано так но конкретно сейчас да он лишний просто чтоб показать что они все одна целая эко система, уберу

2024-10-18 20:15 UTC, Silencemess1ah commented on src/main/java/faang/school/achievement/publisher/achievement/UserAchievementPublisher.java
> +        log.debug("Sent message with id : {} in {} channel", message.getId(),
явно указать название юзерАчивДто ? ок

2024-10-18 20:15 UTC, Silencemess1ah commented on src/main/java/faang/school/achievement/publisher/achievement/UserAchievementPublisher.java
> +@Builder
Это щас экспертиза разберется что лишнее что нет

2024-10-18 20:15 UTC, Silencemess1ah commented on src/main/java/faang/school/achievement/listener/comment/CommentEventListener.java
> +            log.debug("Sending sending comment event to all handlers");
Не правда всего лишь два раза написал )

2024-10-18 20:16 UTC, Silencemess1ah commented on src/main/java/faang/school/achievement/handler/comment/EvilCommenterAchievementHandler.java
> +        Achievement evilCommenter = achievementRepository.findById(9L).orElseThrow();
Что не так ?) Вот конкретно, я пока заменил поход в кэш пока жду его мержа на поход в БД - всё(

2024-10-19 14:31 UTC, mysosnovskaya requested changes

2024-10-19 14:31 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/handler/comment/EvilCommenterAchievementHandler.java
> +            achievementService.createProgressIfNecessary(userId, achievementId);
Работу с прогрессом можно вынести как минимум в отдельный метод (в achievementService), а может быть и в отдельный класс даже

2024-10-19 14:31 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/service/achievement/AchievementService.java
> +    @Transactional
Пустой строки не хватает здесь и после метода тоже

2024-10-19 14:31 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/dto/comment/CommentEventDto.java
> +public class CommentEventDto {
А этот ивент приходит в случае нового комментария, верно? Тогда лучше назвать NewCommentEventDto. Т.к. событие (event) происходит из-за какого-то действия и в нашем случае лучше обозначить явно, что это из-за нового комментария

2024-10-19 14:31 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/handler/comment/CommentEventHandler.java
> +public abstract class CommentEventHandler {
И здесь соответственно тоже NewCommentEventHandler

2024-10-19 14:31 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/handler/comment/CommentEventHandler.java
> +public abstract class CommentEventHandler {
Если хочешь, можешь подумать над абстракцией: сделать общий хэндлер для всех ивентов, а не только для нового комментария. Это было бы идеально, т.к. мы уже знаем, что нам это точно понадобится (у нас много задач на разные достижения по разным ивентам)

2024-10-20 08:28 UTC, Silencemess1ah commented on src/main/java/faang/school/achievement/handler/comment/CommentEventHandler.java
> +public abstract class CommentEventHandler {
Так я сделал до этого... просто пока как маркер для понимания что это за классы и для чего (интерфейс делал) Паша мне написал мол зачем оно надо, если пока не используешь и никаких методов в нем нет кроме наследования..

2024-10-20 08:29 UTC, Silencemess1ah commented on src/main/java/faang/school/achievement/handler/comment/CommentEventHandler.java
> +public abstract class CommentEventHandler {
6ой комментарий от него

2024-10-20 19:30 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/handler/comment/EvilCommenterAchievementHandler.java
> +                    .proceedAchievementProgress(userId,achievementId);
Точка должна быть на предыдущей строке по кодстайлу, а после запятой - пробел

2024-10-20 19:30 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/handler/comment/EvilCommenterAchievementHandler.java
> +                UserAchievement userAchievement = UserAchievement.builder()
Вот здесь использование билдера оправданно, т.к. это не маппинг одного объекта в другой, а создание нового объекта из разных данных

2024-10-20 19:30 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/listener/comment/CommentEventListener.java
> +public class CommentEventListener implements MessageListener {
NewCommentEventListener?

2024-10-20 19:30 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/handler/comment/CommentEventHandler.java
> +public abstract class CommentEventHandler {
Похоже, что тут можно сделать не интерфейс-маркер, а абстрактный класс с общей логикой. Но это задача со звездочкой, посложнее) Мы знаем (вроде), что у всех слушателей будет список хэнделров и objectMapper в качестве полей. У всех будет преобразование из message в ивент-дто нужного типа. У всех будет одинаковая обработка ошибок, можно даже логгирование вынести. В общем, предлагаю ещё подумать, но ты можешь отказаться и оставить как есть - такое тоже приму)

2024-10-23 12:37 UTC, mysosnovskaya approved these changes

2024-10-23 12:37 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/handler/comment/EvilCommenterAchievementHandler.java
> +                    proceedAchievementProgress(userId, achievementId);
Я очень извиняюсь, но точка всё-таки была расположена правильно. Это у меня какое-то минутное помутнение было :( Перенеси точку обратно и можешь сам ПР смержить, т.к. в остальном всё ок)

2024-10-23 12:37 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/handler/comment/EvilCommenterAchievementHandler.java
> +        Achievement evilCommenter = achievementCache.getAchievement(evilCommenterAchievement);
Вообще мне казалось, что тут есть общая логика для всех достижений. Нам же всё равно каждый раз придется проверять, есть ли уже у пользователя это достижение и если нет, то проверять количество очков и при достижении нужного количества - выдавать ачивку. Разница только в том, какое именно достижение. Вот я хотела такую общую логику увидеть в абстрактном классе NewCommentEventHandler. Но т.к. у нас пока никаких других достижений по комментариям не реализовано, то, наверное, не так просто понять, как обобщить. Можешь оставить так, как есть) Но если интересно - попробуй вынести общий код в абстрактный класс и тогда отправляй на доработку

2024-10-23 14:08 UTC, merged