BJS2-27493: Получение достижения "Всех люблю" (sub)
CorporationX/achievement_service pull request #234
Opened 2024-10-15 16:36 UTC by soulasphyxia

2024-10-16 04:43 UTC, ArstanSubanov approved these changes
Вроде всё хорошо, оставил свои рекомендации)

2024-10-16 04:43 UTC, ArstanSubanov commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +        return Optional.ofNullable(cache.get(title));
Думаю, тут можно сразу проверять, что achievment не пустой и бросать исключение, потому что в кэш будут обращаться из разных мест и везде нужно будет писать проверку на то, что он не пустой)

2024-10-16 04:43 UTC, ArstanSubanov commented on src/main/java/faang/school/achievement/handler/like_event/LikeEventHandler.java
> +public abstract class LikeEventHandler extends AbstractEventHandler<LikeEventDto> implements EventHandler<LikeEventDto> {
Думаю, EventHandler<LikeEventDto> тут лишняя, так как AbstractEventHandler<LikeEventDto> уже реализует EventHandler<>)

2024-10-16 04:43 UTC, ArstanSubanov commented on src/main/java/faang/school/achievement/handler/AbstractEventHandler.java
> +    @Retryable(retryFor = ObjectOptimisticLockingFailureException.class, maxAttempts = 5, backoff = @Backoff(delay = 5000))
Мне писали в ПР выносить параметры в конфиг)

2024-10-16 14:23 UTC, soulasphyxia commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +        return Optional.ofNullable(cache.get(title));
я решил сделать по аналогии с репозиторием, там Optional возвращается, но думаю да, твой вариант лучше.

2024-10-16 14:23 UTC, soulasphyxia commented on src/main/java/faang/school/achievement/handler/like_event/LikeEventHandler.java
> +public abstract class LikeEventHandler extends AbstractEventHandler<LikeEventDto> implements EventHandler<LikeEventDto> {
ты прав, не заметил!

2024-10-16 14:39 UTC, soulasphyxia commented on src/main/java/faang/school/achievement/handler/AbstractEventHandler.java
> +    @Retryable(retryFor = ObjectOptimisticLockingFailureException.class, maxAttempts = 5, backoff = @Backoff(delay = 5000))
сделал, но не так как у тебя в ПР, не нашел как в параметр аннотации значение переменной записать

2024-10-16 15:17 UTC, SharkB38 approved these changes

2024-10-16 17:31 UTC, ArstanSubanov commented on src/main/java/faang/school/achievement/handler/AbstractEventHandler.java
> +    @Retryable(retryFor = ObjectOptimisticLockingFailureException.class, maxAttempts = 5, backoff = @Backoff(delay = 5000))
У тебя этот способ работает? У меня не работал, поэтому я откатил обратно к константе(

2024-10-16 17:35 UTC, SharkB38 commented on src/main/java/faang/school/achievement/handler/AbstractEventHandler.java
> +    @Retryable(retryFor = ObjectOptimisticLockingFailureException.class, maxAttempts = 5, backoff = @Backoff(delay = 5000))
Не работал в плане? Метод не вызывался повторно?

2024-10-16 17:43 UTC, ArstanSubanov commented on src/main/java/faang/school/achievement/handler/AbstractEventHandler.java
> +    @Retryable(retryFor = ObjectOptimisticLockingFailureException.class, maxAttempts = 5, backoff = @Backoff(delay = 5000))
Я не проверял повторные вызовы, но у меня в application.yaml параметры подсвечивались, что они не используются, я начал разбираться и выяснил, что для внедрения параметров из конфига, нужно заморочиться и использовать SpEL, отдельный бин для каждого параметра или retryTemplate. Поэтому я спросил у Маши, и она ответила что пока оставляем константы)

2024-10-16 18:11 UTC, soulasphyxia commented on src/main/java/faang/school/achievement/handler/AbstractEventHandler.java
> +    @Retryable(retryFor = ObjectOptimisticLockingFailureException.class, maxAttempts = 5, backoff = @Backoff(delay = 5000))
да, у меня работает, там надо параметр другой использовать(название такое же, только в конце expression) и он распознает из конфига значения

2024-10-16 18:43 UTC, ArstanSubanov commented on src/main/java/faang/school/achievement/handler/AbstractEventHandler.java
> +    @Retryable(retryFor = ObjectOptimisticLockingFailureException.class, maxAttempts = 5, backoff = @Backoff(delay = 5000))
Сделал как у тебя и проверил выключив редис, вроде работает, спасибо) А то интернет всё усложнял)

2024-10-16 19:33 UTC, mysosnovskaya requested changes

2024-10-16 19:33 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +    @PostConstruct
Интересно, почему сделал именно через PostConstruct?
Поясню, что мне не очень нравится в текущем варианте: у тебя в классе появляется поле achievementRepository, которое нужно только для того, чтобы заполнить мапу cache. А вообще не подразумевается, что этим полем ещё где-то в этом классе нужно будет пользоваться. А поле есть. В будущем другие разработчики могут добавить в класс методы, использующие репозиторий (потому что он есть), хотя вообще логически это неверно. Как можно по-другому: создать обычный конструктор, которые примет AchievementRepository и заполнит с его помощью кэш. А как поле сохранять этот репозиторий не будет)

2024-10-16 19:33 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/handler/AbstractEventHandler.java
> +            log.info("User %d already has achievement %d".formatted(userId, achievement.getId()));
А насколько это нормальная ситуация? Может быть в warn записать?

2024-10-16 19:33 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/handler/AbstractEventHandler.java
> +        achievementService.createProgressIfNecessary(userId, achievementId);
Как будто бы вся эта логика с прогрессом должна быть не в AbstractEventHandler, а в специальном отдельном классе. Что думаешь?

2024-10-17 10:04 UTC, soulasphyxia commented on src/main/java/faang/school/achievement/handler/AbstractEventHandler.java
> +        achievementService.createProgressIfNecessary(userId, achievementId);
да, ты права, вынес в отдельный сервис!

2024-10-17 10:08 UTC, soulasphyxia commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +    @PostConstruct
я писал код по описанию из задачи на кэш достижений, она небольшая, поэтому я ее решил сразу сюда запихнуть, пока никто не начинал делать ачивки, там также просили @PostConstruct, но ты польностью права, когда используешь lombok забываешь что вообще-то конструкторы можно самому писать и выносить туда логику

2024-10-17 10:11 UTC, soulasphyxia commented on src/main/java/faang/school/achievement/handler/AbstractEventHandler.java
> +            log.info("User %d already has achievement %d".formatted(userId, achievement.getId()));
а, ну вообще, да, странно, что произошла такая ситуация, что пользователю пытаются начислить ачивку, которая у него уже есть... спасибо, что заметила!

2024-10-17 13:33 UTC, aassylkhan approved these changes
Супер!

2024-10-17 13:33 UTC, aassylkhan commented on src/main/java/faang/school/achievement/handler/AbstractEventHandler.java
> +    @Retryable(retryFor = ObjectOptimisticLockingFailureException.class, maxAttemptsExpression = "${retryable.max-attempts}", backoff = @Backoff(delayExpression = "${retryable.delay}"))
Классно написано

2024-10-17 19:05 UTC, mysosnovskaya approved these changes

2024-10-17 19:05 UTC, merged