Feature bjs2 26174 cache for achievement service
CorporationX/achievement_service pull request #238
Opened 2024-10-16 06:51 UTC by Silencemess1ah

- cache + tests

2024-10-16 09:12 UTC, GusevVrn commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +    public Achievement getAchievement(@NotBlank(message = "Title can't be neither blank nor null!")
для notBlank vaildated не нужен?

2024-10-16 09:12 UTC, GusevVrn commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +            throw new RuntimeException();
NoSuchElementException

2024-10-16 09:12 UTC, GusevVrn commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +    private final Map<String, Achievement> cache = new HashMap<>();
Название бы попонятнее.

Если у тебя инициализация где-то есть, то может тут не объявлять hashMap?
Вообще у меня пока все понимание не пришло как мы с ачивками работаем, будем обновлять или нет. 
Если обновляем, то я бы в сторону concurrency map подумал бы.
Если обновления не будет, то hashmap норм.

2024-10-16 09:12 UTC, GusevVrn commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +        achievementRepository.findAll().forEach(achievement ->
вот если там убираем hashmap то тут collect(Collectors) использовать, он вроде по дефолту в hashmap собирает

2024-10-16 09:12 UTC, GusevVrn commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +                achievementCache.getCache().put(achievement.getTitle(), achievement));
а может быть такое что у нескольких ачивок будет одинаковое название, тогда тут что произойдет?

2024-10-16 09:19 UTC, Silencemess1ah commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +                achievementCache.getCache().put(achievement.getTitle(), achievement));
А как такое возможно? Мы ж с базы их поднимаем на долгий срок просто чтоб к ней не ходить каждый раз, там title VARCHAR(128) NOT NULL UNIQUE так что они уникальны как ни крути, типо летят проверки на ачивки и мы ходим в кэш(хэш мапу) даже если у нас 100 ачивок (что врят ли) один раз сходили запилили хэш мап и дергаем ее, один раз только заполнить и база гарантирует нам что тайтл - Юник

2024-10-16 09:22 UTC, Silencemess1ah commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +    private final Map<String, Achievement> cache = new HashMap<>();
Ну может мы и будем обновлять но типо руками  - придумали + 2 ачивки прописали в конфиге и полетели на них проверки после рестарта, куда понятней?) Кэш и есть кэш или типо achievementCache? я уже так и написал и не мог понять че тест ругается на меня а он не понимал к классу я обращаюсь или к хэш мапе)

2024-10-16 09:24 UTC, Silencemess1ah commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +        achievementRepository.findAll().forEach(achievement ->
Я честно фиг знает как правильней, я вынес туда потому что не тестилось без объявления ни в какую, мне кажется разницы ни какой не будет, а мож и будет

2024-10-16 09:25 UTC, Silencemess1ah commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +                achievementCache.getCache().put(achievement.getTitle(), achievement));
В данный момент их там 8 + 1 я докинул (хотя в описании написано что все есть уже но это не так)

2024-10-16 20:21 UTC, mysosnovskaya requested changes

2024-10-16 20:21 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +    @PostConstruct
Это очень странная логика, что в PostConstruct у AchievementService инициализируется achievementCache. Надо придумать, как сделать по-другому) Пока вариантов писать не буду, оставлю как самостоятельное задание, но если что, то готова обсудить)

2024-10-18 15:40 UTC, mysosnovskaya requested changes

2024-10-18 15:40 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/config/cache/AchievementCache.java
> +    @PostConstruct
Уже лучше (мне нравится, что кэш теперь инициализируется внутри), но всё равно не понимаю, почему PostConstruct, а не обычный конструктор?)

2024-10-18 15:40 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/config/cache/AchievementCache.java
> +    public Map<String, Achievement> updateCache() {
Вроде бы у нас пока нет такой логики, что ачивки могут добавляться/удаляться, пока приложение работает. Т.е. пока приложение запущено, метод achievementRepository.findAll() всегда будет возвращать одно и то же. Идея хорошая, но на данный момент не имеет обоснованности, а значит является переусложнением)

2024-10-18 19:58 UTC, Silencemess1ah commented on src/main/java/faang/school/achievement/config/cache/AchievementCache.java
> +    @PostConstruct
Потому что в ТЗ так сказано:
4.1 Используем готовый бин AchievementRepository и его метод findAll, который возвращает все достижения, доступные в БД.
4.2Используем аннотацию @PostConstruct, чтобы создать метод инициализации кэша при старте всего сервиса.

2024-10-18 20:08 UTC, Silencemess1ah commented on src/main/java/faang/school/achievement/config/cache/AchievementCache.java
> +    public Map<String, Achievement> updateCache() {
Убрал scheduled и апдейт отрефакторил

2024-10-19 14:33 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/config/cache/AchievementCache.java
> +    @PostConstruct
Да, увидела. Хотя я и не понимаю, почему требуют именно так (т.к. из-за этого нам приходится держать лишнее поле с репозиторием, которое нам в целом и не нужно) и переделала бы на обычный конструктор всё равно. Но давай оставим по тз)

2024-10-19 14:34 UTC, merged