BJS2-27121 Get Achievements from Redis cache
CorporationX/achievement_service pull request #245
Opened 2024-10-18 02:05 UTC by amilosh

2024-10-18 19:47 UTC, 20cognosce requested changes

2024-10-18 19:47 UTC, 20cognosce commented on src/main/java/faang/school/achievement/repository/AchievementRepository.java
> +    @Query("SELECT a FROM Achievement a LEFT JOIN FETCH a.userAchievements")
А внутри транзакции ты не можешь фетчнуть? Через хибернейт

2024-10-18 19:47 UTC, 20cognosce commented on src/main/java/faang/school/achievement/config/app/AppConfig.java
> +    public ObjectMapper objectMapper() {
Qualifier

2024-10-18 19:47 UTC, 20cognosce commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +        return achievementCache.getFromCache(fromDb.getTitle());
Зачем ты туда-сюда перегоняешь достижение?
Ты достал из БД - сразу его отдай
Зачем ты его сначала кладешь в кеш, а затем имея его в руках - всё равно идешь в кеш...

Порефактори этот метод

2024-10-18 19:47 UTC, 20cognosce commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +    private Achievement findByTitle(String title) {
Отдельный метод на две строчки, ну...

2024-10-18 19:47 UTC, 20cognosce commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +        List<Achievement> achievements = achievementRepository.findAllWithUsers();
Вот тут как раз, почему ты в репозиторий идешь, а не через сервис? И в сервисе транзакцию навесь, в которой сфетчи юзеров

2024-10-18 19:47 UTC, 20cognosce commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +        List<Achievement> achievements = achievementRepository.findAllWithUsers();
Только проверь, что не выпадает LazyInitializationException обязательно

2024-10-18 20:20 UTC, amilosh commented on src/main/java/faang/school/achievement/repository/AchievementRepository.java
> +    @Query("SELECT a FROM Achievement a LEFT JOIN FETCH a.userAchievements")
Я пробовал спринговую транзакцию повесить
```
    @Transactional
    @PostConstruct
    public void fillAchievements() {
        List<Achievement> achievements = achievementRepository.findAllWithUsers();
        addToCache(achievements);
    }
```
Но при PostConstract транзакцию не может создать.

На stackoverflow расписаны обходные пути, но мне с Query показался самымы лаконичиным. Тем более, что в другом сервисе уже использовался такой подход (изначально что в мастер ветке были).

2024-10-18 20:21 UTC, amilosh commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +        List<Achievement> achievements = achievementRepository.findAllWithUsers();
Сейчас попробую через сервис, создастся ли транзакция.

2024-10-18 20:28 UTC, amilosh commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +        List<Achievement> achievements = achievementRepository.findAllWithUsers();
Пробовал в лоб в AchievementCache добавить 
private final AchievementService achievementService;
но тогда циклическая зависимость будет

2024-10-18 20:51 UTC, amilosh commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +        List<Achievement> achievements = achievementRepository.findAllWithUsers();
В общем, во время PostConstruct с помощью Transactional LazyInitializationException выпадает.

Из обходных путей:
- сделать как я через query
- как-то вручную транзакцию создать
- сделать fill когда аплик полностью проинициализируеся и в спринге есть листенер

Если решение в query не подходит, скажи, буду другие сспособы пробовать.

2024-10-18 20:58 UTC, amilosh commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +        return achievementCache.getFromCache(fromDb.getTitle());
Я сразу начал делать как в других сервисах, что в AchievementService использовать Achievement.
Но когда стал класть achievement в Redis в виде json, то там бескоонечный json получался.
Поэтому сделал AchievementDto.

И получалось, что в сервис приходит Achievement, а маппер в сервисе мы не используем.
Пришлось выбирать, либо маппер в сервисе использовать, либо полностью с AchievementDto работать.

И получается, когда делаю Achievement fromDb = findByTitle(title); а на фронт нужно вернуть dto то пришлось бы мапить внутри сервиса.

2024-10-18 20:59 UTC, amilosh commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +        return achievementCache.getFromCache(fromDb.getTitle());
В общем, сделал, чтобы 
public void addToCache(Achievement achievement)
был не войдом, а dto возвращал

2024-10-18 21:04 UTC, amilosh commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +    private Achievement findByTitle(String title) {
Просто когда делаю
```
        Achievement fromDb = findByTitle(title);
        return achievementCache.addToCacheAndReturn(fromDb);
```
то мне это легче читается

а когда 
```
        Achievement fromDb = achievementRepository.findByTitle(title)
                .orElseThrow(() -> new ResourceNotFoundException("Achievement", title));
        return achievementCache.addToCacheAndReturn(fromDb);
```
то вот это отлавливание создает много визуалного шума

2024-10-18 21:17 UTC, amilosh commented on src/main/java/faang/school/achievement/config/app/AppConfig.java
> +    public ObjectMapper objectMapper() {
Во всех микросервисах используется ObjectMapper objectMapper именно с такой реализацией (с JavaTimeModule). И мы договоились такой он будет по дефолту для всех микросервисов. И будет вызываться 
private final ObjectMapper objectMapper;

А если кто-то захочет создать отличающийся - пусть ставит кваливаер. (хотя пока таких случаев ещё не ыбло вроде)

2024-10-18 21:18 UTC, amilosh commented on src/main/java/faang/school/achievement/repository/AchievementRepository.java
> +    @Query("SELECT a FROM Achievement a LEFT JOIN FETCH a.userAchievements")
Оставить как есть с query?

2024-10-18 21:18 UTC, amilosh commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +        List<Achievement> achievements = achievementRepository.findAllWithUsers();
Оставить как есть с query?

2024-10-18 21:19 UTC, amilosh commented on src/main/java/faang/school/achievement/config/app/AppConfig.java
> +    public ObjectMapper objectMapper() {
Оставить без Quallifier.

2024-10-18 21:20 UTC, amilosh commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +        return achievementCache.getFromCache(fromDb.getTitle());
```
    @Transactional(readOnly = true)
    public AchievementDto getByTitle(String title) {
        AchievementDto fromCache = achievementCache.getFromCache(title);
        if (fromCache != null) {
            return fromCache;
        }

        Achievement fromDb = findByTitle(title);
        return achievementCache.addToCacheAndReturn(fromDb);
    }
```

так пойдёт?

2024-10-18 21:21 UTC, amilosh commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +    private Achievement findByTitle(String title) {
Оставить так Achievement fromDb = findByTitle(title);?

2024-10-21 14:41 UTC, amilosh commented on src/main/java/faang/school/achievement/repository/AchievementRepository.java
> +    @Query("SELECT a FROM Achievement a LEFT JOIN FETCH a.userAchievements")
Надо ипользовать @EntityGraph

2024-10-21 14:42 UTC, amilosh commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +        List<Achievement> achievements = achievementRepository.findAllWithUsers();
Надо ипользовать @entitygraph

2024-10-21 14:43 UTC, amilosh commented on src/main/java/faang/school/achievement/config/app/AppConfig.java
> +    public ObjectMapper objectMapper() {
Без квалифаера.

2024-10-21 14:47 UTC, amilosh commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +        return achievementCache.getFromCache(fromDb.getTitle());
Сделать маппинг из entity в dto, а в редис сохранить асинхронно.

2024-10-21 14:47 UTC, amilosh commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +    private Achievement findByTitle(String title) {
Оставил как у меня на мой вкус.

2024-10-21 21:01 UTC, 20cognosce approved these changes

2024-10-21 21:01 UTC, 20cognosce commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +    }
Троится в глазах
Зачем...

2024-10-21 21:01 UTC, 20cognosce commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +    @Async
И это не будет работать если ты вызываешь метод из другого метода внутри класса

2024-10-21 21:01 UTC, 20cognosce commented
Порефактори эти методы можешь сам вмёрджить

2024-10-22 11:11 UTC, amilosh commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +    }
убрал addToCache(AchievementDto dto) оставил только addToCache(Achievement achievement)

2024-10-22 11:15 UTC, amilosh commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +    @Async
перенес `@Async` в addToCache(Achievement achievement)
и добавил entytyGraph чтоб лэйзи эекзепшена не было

2024-10-22 11:15 UTC, merged