Features/publication of achievement bjs2 26937
CorporationX/achievement_service pull request #251
Opened 2024-10-18 18:33 UTC by DankeVilletti

2024-10-20 21:34 UTC, Peregruzochka reviewed
cool
мне все нравится
попробуй теперь себя в интеграционных тестах)

2024-10-20 21:34 UTC, Peregruzochka commented on src/main/java/faang/school/achievement/publish/publisher/AchievementEventPublisher.java
> +        log.info("Send LikeEvent to Brokers channel: {} , message: {}", message, likeEventChannel);
тут, наверное, не **like**EventChannel, а что-то другое нужно придумать, ну и логи подправить)

2024-10-23 16:15 UTC, mrkorolev reviewed
Неплохо было бы ссылку на таску в jira)

2024-10-23 16:15 UTC, mrkorolev commented on src/main/java/faang/school/achievement/dto/achievement/UserAchievementEventDto.java
> +}
Валидацию не надо делать тут?

2024-10-23 16:15 UTC, mrkorolev commented on src/main/java/faang/school/achievement/model/Achievement.java
> +    @Enumerated(EnumType.STRING)
Почему ORDINAL решил убрать? Я просто за то, чтобы в базе лежало число - текст будет копироваться, но занимает он больше места чем число. В принципе это сломается если менять порядок констант в Enum, короче палка о двух концах :)

2024-10-24 18:05 UTC, DankeVilletti commented on src/main/java/faang/school/achievement/model/Achievement.java
> +    @Enumerated(EnumType.STRING)
@20cognosce что здесь лучше?

2024-10-26 12:32 UTC, 20cognosce commented on src/main/java/faang/school/achievement/model/Achievement.java
> +    @Enumerated(EnumType.STRING)
String

2024-10-26 12:37 UTC, 20cognosce approved these changes

2024-10-26 12:39 UTC, 20cognosce commented
Конфликт правь и можно заливать

2024-10-29 18:25 UTC, 20cognosce requested changes

2024-10-29 18:25 UTC, 20cognosce commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +    @PublishAchievementEvent
Ты уверен, что аспект сработает на приватном методе, так еще и при вызове из другого метода того же класса? Боюсь здесь будет баг.
Проверь пожалуйста

2024-10-29 18:25 UTC, 20cognosce commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +        userAchievementRepository.save(userAchievement);
Ох. Нет.
save не сохраняет твою сущность в базу. Flush и commit выполняется обработчиком аннотации @Transactional

Рано ты паблишишь событие, настоящий запрос в базу может упасть к тому моменту, как ты отослал событие

Либо делай тут flush, либо над @transactional методом вешай

2024-10-30 15:41 UTC, 20cognosce approved these changes

2024-10-30 15:41 UTC, merged