BJS2-27492: Получение достижения "Рекурсия-рекурсия"
CorporationX/achievement_service pull request #256
Opened 2024-10-20 15:27 UTC by ArstanSubanov

2024-10-20 17:36 UTC, SharkB38 approved these changes

2024-10-20 17:36 UTC, SharkB38 commented on src/main/java/faang/school/achievement/config/redis/RedisConfig.java
> +    public RedisTemplate<String, AchievementEvent> achievementEventRedisTemplate() {
Он же нигде не используется?

2024-10-20 17:36 UTC, SharkB38 commented on src/main/java/faang/school/achievement/config/redis/RedisConfig.java
> +            Map<String, ChannelTopic> channelTopics) {
Крутое решение, а где они в мапы собираются?

2024-10-20 17:36 UTC, SharkB38 commented on src/main/java/faang/school/achievement/config/redis/RedisConfig.java
> +    public RedisTemplate<String, AchievementEvent> achievementEventRedisTemplate() {
А все увидел

2024-10-20 19:05 UTC, wmwmaks commented on src/main/java/faang/school/achievement/config/redis/RedisConfig.java
> +            Map<String, ChannelTopic> channelTopics) {
Мне тоже интересно как адаптеры в мапу эту попадают. Не понял

2024-10-20 19:06 UTC, wmwmaks commented on src/main/java/faang/school/achievement/handler/achievement/RecursionAchievementHandler.java
> +    protected String getAchievementTitle() {
а тут не получится тоже аргументом через Value передавать, как в редис конфиге с топиками делаем?

2024-10-20 19:07 UTC, wmwmaks approved these changes
👍

2024-10-21 02:52 UTC, ArstanSubanov commented on src/main/java/faang/school/achievement/config/redis/RedisConfig.java
> +            Map<String, ChannelTopic> channelTopics) {
Как понял, принцип работы такой же, как и внедрение списка, Spring же автоматически может внедрить нам список бинов, также и может внедрить и мапы, только вместо ключей всегда будет имя бина, а значением сам бин, и как-то изменить это правило в конструкторе или где-либо ещё нельзя)

2024-10-21 02:54 UTC, ArstanSubanov commented on src/main/java/faang/school/achievement/handler/achievement/RecursionAchievementHandler.java
> +    protected String getAchievementTitle() {
К сожалению не получится, так как это же не бин, а просто параметр, их конечно можно в какой-то ConfigParams выделить, но как Маша писала мне в ПР, это будет неочевидно и все просто забудут про этот класс)

2024-10-21 04:57 UTC, SharkB38 commented on src/main/java/faang/school/achievement/handler/achievement/RecursionAchievementHandler.java
> +    protected String getAchievementTitle() {
Может тогда переменные под это дело завести?

2024-10-21 05:34 UTC, ArstanSubanov commented on src/main/java/faang/school/achievement/handler/achievement/RecursionAchievementHandler.java
> +    protected String getAchievementTitle() {
Не совсем понял что ты имеешь ввиду, переменную title я же уже создаю через @Value. Или ты по-другому создание хотел предложить?)

2024-10-21 06:35 UTC, RuslanIovlev commented on src/main/java/faang/school/achievement/config/redis/RedisConfig.java
> +            Map<String, ChannelTopic> channelTopics) {
Классное решение
Мне маша писала подумать как решить проблему с увеличением параметров в контейнере
Если это работает, то прям круто

2024-10-21 06:42 UTC, RuslanIovlev commented
👌🏻

2024-10-21 06:43 UTC, RuslanIovlev approved these changes

2024-10-21 07:19 UTC, SharkB38 commented on src/main/java/faang/school/achievement/handler/achievement/RecursionAchievementHandler.java
> +    protected String getAchievementTitle() {
Я вообще не о том подумал, тут все круто по моему

2024-10-21 12:23 UTC, soulasphyxia approved these changes

2024-10-21 12:55 UTC, SharkB38 commented on src/main/resources/application.yaml
> +          title: Recursion-recursion
Кстати, здесь как я понял чисто название ачивки? А почему поместил здесь, а не в achievements?

2024-10-21 13:00 UTC, ArstanSubanov commented on src/main/resources/application.yaml
> +          title: Recursion-recursion
Точно, спасибо, исправлю)

2024-10-21 19:12 UTC, mysosnovskaya requested changes

2024-10-21 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/listener/AchievementEventListener.java
> +        handlers.forEach(handler -> handler.handle(achievementEvent));
А вот эта вся логика разве не будет общей для всех слушателей? Разница будет только в типе, верно? Хотя какие тут ещё типы могут быть, у нас же здесь только достижения?

2024-10-21 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/publisher/AchievementMessagePublisher.java
> +                                       @Qualifier("achievementChannelTopic") ChannelTopic channelTopic) {
Может так?
https://discord.com/channels/1102662981743030334/1267555771944796171/1297874842082607207

2024-10-21 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/service/AchievementServiceImpl.java
> +    @Cacheable(value = "achievementService::hasAchievement", key = "#userId" + '.' + "#achievementId")
Круто!! 👍

2024-10-21 19:12 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +          title: Recursion-recursion
И ещё с заглавной буквы почему-то)

2024-10-23 19:51 UTC, mysosnovskaya approved these changes

2024-10-23 19:51 UTC, merged