BJS2-26167: Получение достижения Собиратора
CorporationX/achievement_service pull request #264
Opened 2024-10-25 18:40 UTC by lowerKamaCase

2024-10-26 12:49 UTC, segaTk reviewed
Супер, нужно немного пересмотреть асинхронный метод

2024-10-26 12:49 UTC, segaTk commented on src/main/java/faang/school/achievement/listener/goal/GoalEventListener.java
> +    public void onMessage(Message message, byte[] pattern) {
Может здесь не хватает аннотации валидации?

2024-10-26 12:49 UTC, segaTk commented on src/main/java/faang/school/achievement/handler/goal/GoalSetCollectorAchievementHandler.java
> +        Achievement achivement = achievementCache.getAchievement(goalName);
Нужно ли здесь определить переменную goalName? Не будет ли ошибки? и пропустил букву е в achivement

2024-10-26 12:49 UTC, segaTk commented on src/main/java/faang/school/achievement/handler/goal/GoalSetCollectorAchievementHandler.java
> +                achivement.getId());
Не выскочит здесь NullPointerException? Нужна проверка и логи

2024-10-26 12:49 UTC, segaTk commented on src/main/java/faang/school/achievement/handler/goal/GoalSetCollectorAchievementHandler.java
> +        if (hasAchievement) {
Может не хватает логирования ещё?

2024-10-26 12:49 UTC, segaTk commented on src/main/java/faang/school/achievement/handler/goal/GoalSetCollectorAchievementHandler.java
> +
Здесь может тоже нужны логи

2024-10-26 13:18 UTC, GusevVrn reviewed
Согласен с Серегой, логов не хватает

2024-10-26 13:18 UTC, GusevVrn commented on src/main/java/faang/school/achievement/handler/goal/GoalSetCollectorAchievementHandler.java
> +    private long pointsNeededToGetCollectorAchievement;
можно как-то value вынести в конфигурацию

2024-10-26 13:18 UTC, GusevVrn commented on src/main/java/faang/school/achievement/handler/goal/GoalSetCollectorAchievementHandler.java
> +        Achievement achivement = achievementCache.getAchievement(goalName);
она же сверху определена

2024-10-26 13:18 UTC, GusevVrn commented on src/main/java/faang/school/achievement/handler/goal/GoalSetCollectorAchievementHandler.java
> +        if (hasAchievement) {
если сделать !hasAchievement то уберем лишнюю строчку в коде

2024-10-26 13:18 UTC, GusevVrn commented on src/main/java/faang/school/achievement/listener/goal/GoalEventListener.java
> +    public void onMessage(Message message, byte[] pattern) {
Если ты про validation, что она в данном коде даст?

2024-10-27 18:28 UTC, lowerKamaCase commented on src/main/java/faang/school/achievement/handler/goal/GoalSetCollectorAchievementHandler.java
> +    private long pointsNeededToGetCollectorAchievement;
так уже ведь из конфигурации значение подтягивается

2024-10-27 18:33 UTC, lowerKamaCase commented on src/main/java/faang/school/achievement/handler/goal/GoalSetCollectorAchievementHandler.java
> +        if (hasAchievement) {
да, это верно, здесь можно избавиться от ретурна.
но тогда весь код станет немного "правее".
и если допустить, что логика когда-нибудь изменится (например, добавится еще условие), то появится еще внутренний if. и так код будет уезжать дальше вправо. и это снизит читаемость.
поэтому мне больше нравится паттерн проверки условия и завершения сценария с ретурн

2024-10-27 18:38 UTC, lowerKamaCase commented on src/main/java/faang/school/achievement/handler/goal/GoalSetCollectorAchievementHandler.java
> +                achivement.getId());
@mysosnovskaya будет ли ок, если 1) в GoalSetEventDto обоим полям Long заменю на long и 2) не буду обкладывать весь код проверками на NPE ?

2024-10-27 18:41 UTC, lowerKamaCase commented on src/main/java/faang/school/achievement/handler/goal/GoalSetCollectorAchievementHandler.java
> +                achivement.getId());
логи добавил, спасибо за коммент

2024-10-27 18:49 UTC, lowerKamaCase commented on src/main/java/faang/school/achievement/handler/goal/GoalSetCollectorAchievementHandler.java
> +                achivement.getId());
логирование добавил только в ветку hasAchievement.
дальше, имхо, логирование избыточно, потому что в achievementService.giveAchievement уже есть логирование

2024-10-27 20:53 UTC, segaTk commented on src/main/java/faang/school/achievement/listener/goal/GoalEventListener.java
> +    public void onMessage(Message message, byte[] pattern) {
Сама идея подсвечивает это, видимо надо

2024-10-28 18:35 UTC, mysosnovskaya requested changes

2024-10-28 18:35 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/handler/goal/GoalSetCollectorAchievementHandler.java
> +                achivement.getId());
> @mysosnovskaya будет ли ок, если 1) в GoalSetEventDto обоим полям Long заменю на long и 2) не буду обкладывать весь код проверками на NPE ?

Да, ок

2024-10-28 18:35 UTC, mysosnovskaya commented on src/main/java/faang/school/achievement/handler/goal/GoalSetCollectorAchievementHandler.java
> +    public void verifyAchievement(GoalSetEventDto goalSetEvent) {
Посмотри, у нас появился абстрактный класс, эта логика не такая же?
https://github.com/CorporationX/achievement_service/blob/unicorn-master-stream6/src/main/java/faang/school/achievement/handler/AbstractEventHandler.java#L23

2024-10-29 12:26 UTC, lowerKamaCase commented on src/main/java/faang/school/achievement/handler/goal/GoalSetCollectorAchievementHandler.java
> +                achivement.getId());
тогда поправил на long)

2024-10-29 19:12 UTC, lowerKamaCase commented on src/main/java/faang/school/achievement/handler/goal/GoalSetCollectorAchievementHandler.java
> +    public void verifyAchievement(GoalSetEventDto goalSetEvent) {
такая же, поправил. теперь extends AbstractEventHandler

2024-10-30 19:46 UTC, mysosnovskaya approved these changes

2024-10-31 05:33 UTC, merged