BJS2-41694 Получение достижения "Собиратора"
CorporationX/achievement_service pull request #319
Opened 2024-12-22 10:15 UTC by Alex15265

[
![sendEvent](https://github.com/user-attachments/assets/e6a32084-e54f-4f2b-be3d-0edcb30a1eec)
![handleEvent](https://github.com/user-attachments/assets/39088884-7d1a-4773-abcf-bf4d69fa247f)
![achievementProgress](https://github.com/user-attachments/assets/83a92189-8b98-456b-bae4-755c5145c6ba)
![userAchievement](https://github.com/user-attachments/assets/f07d3073-91f0-4ee2-b2f5-f4bb53eb8a6f)
![achievementServiceTests](https://github.com/user-attachments/assets/55bd8975-5342-4d62-80b4-f92fe91f52ed)
](url)

2024-12-23 21:04 UTC, jibulani requested changes
хорошо, есть пара моментов для доработки

2024-12-23 21:04 UTC, jibulani commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +public class AchievementCache {
почему сделал? это в задаче "Кэширование достижений" делается

2024-12-23 21:04 UTC, jibulani commented on src/main/java/faang/school/achievement/utils/AsyncEventHandlerProcessor.java
> +            progress.setUpdatedAt(LocalDateTime.now());
есть же `@UpdateTimestamp` над полем updatedAt, по идее сработает автоматически

2024-12-23 21:04 UTC, jibulani commented on src/main/java/faang/school/achievement/utils/AsyncEventHandlerProcessor.java
> +                achievementService.giveAchievement(userAchievement);
сделай, пожалуйста, ребейз и отправь в топик событие о достижении

2024-12-24 05:25 UTC, Alex15265 commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +public class AchievementCache {
В условиях задачи в 6 пункте описано: "CollectorAchievementHandler должен получать нужное достижение из кэша достижений по его названию"

2024-12-24 05:29 UTC, Alex15265 commented on src/main/java/faang/school/achievement/utils/AsyncEventHandlerProcessor.java
> +            progress.setUpdatedAt(LocalDateTime.now());
Согласен, не посмотрел - уберу здесь

2024-12-24 06:11 UTC, Alex15265 commented on src/main/java/faang/school/achievement/cache/AchievementCache.java
> +public class AchievementCache {
По умолчанию кэша не было - сделал сам

2024-12-24 06:14 UTC, Alex15265 commented on src/main/java/faang/school/achievement/utils/AsyncEventHandlerProcessor.java
> +                achievementService.giveAchievement(userAchievement);
Сделано!

2024-12-24 16:42 UTC, jibulani approved these changes
супер!

2024-12-24 16:42 UTC, merged