Feature bc 5790
CorporationX/achievement_service pull request #38
Opened 2023-09-04 11:31 UTC by TowBoat39

2023-09-06 11:37 UTC, czar777 approved these changes

2023-09-06 11:37 UTC, czar777 commented on src/main/resources/application.yaml
> +        recommendation: recommendation_channel
В YAML-файлах не рекомендуется использовать названия полей с нижним подчеркиванием, потому что YAML использует подчеркивание для разделения ключей в мапах и для обозначения уровней вложенности.
Вместо нижних подчеркиваний можно использовать camelCase или дефисы

2023-09-06 11:37 UTC, czar777 commented on src/main/resources/achievement/achievement.properties
> +recommendation.points=10
кодирование улетело

2023-09-06 11:37 UTC, czar777 commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +    }
Чтобы постоянно не ходит в базу за Achievement в мастер добавлено кэширование, подтяни изменения

2023-09-06 11:37 UTC, czar777 commented on src/main/java/faang/school/achievement/listener/RecommendationEventListener.java
> +public class RecommendationEventListener extends AbstractEventListener<RecommendationEventDto> implements MessageListener {
MessageListener можно вынести в абстрактный класс чтобы не писать каждый раз

2023-09-06 11:37 UTC, czar777 commented on src/main/java/faang/school/achievement/handler/AbstractNiceGuyAchievementHandler.java
> +                    .version(1)
version используется для optimistic lock, его не нужно создавать, она автоматические создастся.

2023-09-06 11:37 UTC, czar777 commented on src/main/java/faang/school/achievement/config/RedisConfig.java
> +    }
это можно не писать потому не никакой уникальной логики и sping boot создаст его сам

2023-09-06 11:37 UTC, czar777 commented on src/main/java/faang/school/achievement/config/RedisConfig.java
> +    RedisMessageListenerContainer redisContainer() {
recommendationEventListener можно получать сразу в параметрах раз он больше нигде не используется

2023-09-08 09:19 UTC, InnMish requested changes

2023-09-08 09:19 UTC, InnMish commented on src/main/java/faang/school/achievement/AchievementServiceApp.java
> +@PropertySource(value = "classpath:achievement/achievement.properties", encoding = "UTF-8")
В спринге можно настроить так, чтобы один ямл подтягивался в другой ямл, и спринг будет их использовать вместе в одном контексте. Может, так попробуем сделать? Просто, чтобы у нас все было унифицировано. А то сейчас и ямл, и пропертис

То есть создаешь не пропертис, а ямл файл, и при этом в общий ямл, где конфиги, этот новый инжектишь. Там будет что-то вроде такой настройки

```
spring:
  config:
    import: classpath:achievement.yml
```
И тогда вот эта аннотация будет не нужна, а доступ к полям также через Value сможем получить, потому что новый маленький ямл как бы расширяет общий большой ямл

2023-09-08 09:19 UTC, InnMish commented on src/main/java/faang/school/achievement/handler/AbstractNiceGuyAchievementHandler.java
> +public class AbstractNiceGuyAchievementHandler implements EventHandler<RecommendationEventDto> {
Думаю, абстрактный тут не нужен же отдельный для каждого события? Абстрактный класс общий для всех событий должен быть) Иначе какой смысл в его абстрактности?

2023-09-08 09:19 UTC, InnMish commented on src/main/java/faang/school/achievement/handler/AbstractNiceGuyAchievementHandler.java
> +        Achievement achievement = achievementService.getAchievement(title);
Тут можно использовать кэш даже напрямую, наверное 
Но в целом окей

2023-09-08 09:19 UTC, InnMish commented on src/main/java/faang/school/achievement/handler/AbstractNiceGuyAchievementHandler.java
> +    private void giveAchievement(RecommendationEventDto event, Achievement achievement, AchievementProgress progress) {
RecommendationEventDto  это только для твоего события NiceGuy же? 
 вот эту конкретную логику должен делать не абстрактный хендлер
Иначе всем остальным тоже придется свои абстрактные классы писать
Давай тут подумаем, как этот класс сделать общим для всех, а логику по найсгай перенести в NiceGuyAchievementHandler или вообще в сервис

2023-09-08 09:19 UTC, InnMish commented on src/main/java/faang/school/achievement/service/AchievementProgressService.java
> +        return achievementProgressRepository.save(achievementProgress);
Сюда еще бы логику проверки перенести
Та часть, которая в методе getAchievementProgress в хендлере в блоке if, я думаю, можно сюда перетащить

2023-09-08 09:19 UTC, InnMish commented on src/main/java/faang/school/achievement/service/AchievementService.java
> +    }
Да, давай напрямую в хендлере к кэшу 
А то специальный бин-обертку создаем, который в общем-то не нужен

2023-09-12 13:21 UTC, InnMish commented on src/main/resources/application.yaml
> +        recommendation: recommendation_channel
Точно 
Давай поправим здесь

2023-09-12 13:21 UTC, InnMish commented on src/main/java/faang/school/achievement/config/RedisConfig.java
> +    RedisMessageListenerContainer redisContainer(RecommendationEventListener recommendationEventListener, InviteEventListener inviteEventListener) {
В одном из сервисов в твоей же задаче уже заворачивали лисенеры в бины MessageListenerAdapter, давай тут тоже так сделаем.
Вообще не критично, и работать так тоже будет, просто в целом это хорошая практика - чем больше задач мы передадим в работу какому-то другому классу, тем легче будет нам в будущем работать, и тем меньше у нас будет потенциальных проблем, и логика будет более гибкая и расширяемая 

Можно о подробностях почитать доку Spring Data, если интересно)

2023-09-13 15:14 UTC, merged