Task 5940: implementation with tests
CorporationX/achievement_service pull request #48
Opened 2023-09-07 10:18 UTC by ipavelbel

2023-09-08 08:45 UTC, YuliaQueen approved these changes

2023-09-08 08:45 UTC, YuliaQueen approved these changes
Не нашла ничего плохого)

2023-09-09 07:44 UTC, InnMish requested changes

2023-09-09 07:44 UTC, InnMish commented on src/main/java/faang/school/achievement/config/RedisConfig.java
> +    public MessageListenerAdapter postAdapter(PostEventListener postEventListener) {
Если они у тебя одинаково называются, то можно явно не писать имя 
Спринг по умолчанию бины так и называет, по имени метода

2023-09-09 07:44 UTC, InnMish commented on src/main/java/faang/school/achievement/config/RedisConfig.java
> +    public MessageListenerAdapter postAdapter(PostEventListener postEventListener) {
Или не работало? По идее должно было..

2023-09-09 07:44 UTC, InnMish commented on src/main/java/faang/school/achievement/listener/PostEventListener.java
> +    private String achievementTitle;
Обычно сначала поля, потом конструкторы)

2023-09-09 07:44 UTC, InnMish commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changeset/achievement_VOO3_insert_writer_ach.sql
название такое, как будто бы это не ноль-ноль-три, а о-о-з 
Проверь, пожалуйста)

2023-09-09 07:44 UTC, InnMish commented on src/main/java/faang/school/achievement/config/RedisConfig.java
Только лишь с целью сокращения строк кода: 
давай попробуем параметры передать в методы бинов сразу

Типа так: 
```
    @Bean
    public ChannelTopic postTopic(@Value("${spring.data.redis.channels.post}") String postChannel) {
        return new ChannelTopic(postChannel);
    }
```
Это должно работать точно также, но у нас зато будет на как минимум 4 строчки меньше кода)

2023-09-09 07:45 UTC, InnMish commented on src/main/java/faang/school/achievement/config/RedisConfig.java
А, отмена, не сработает) 
Там же в контейнер надо передавать)))))

2023-09-10 11:30 UTC, ipavelbel commented on src/main/java/faang/school/achievement/config/RedisConfig.java
> +    public MessageListenerAdapter postAdapter(PostEventListener postEventListener) {
> 

пишет Could not autowire. No beans of 'MessageListenerAdapter' type found. работает если просто имя прописать, без Qualifier

2023-09-10 11:32 UTC, ipavelbel commented on src/main/java/faang/school/achievement/listener/PostEventListener.java
> +    private String achievementTitle;
> Обычно сначала поля, потом конструкторы)

виноват)

2023-09-10 13:01 UTC, merged